version: '3.1'

services: 

    db:
        image: device-management-db
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: pwd1212
        volumes: 
            - ./datadir:/var/lib/mysql
        ports:
            - 3306:3306
    
    adminer:
        image: adminer
        ports:
            - 8080:8080
