name: CI
on: push
jobs:
  build:
    env:
      DB_DATABASE: dm_test
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: 127.0.0.1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn testci
